# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditVendors50.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editVendors50(object):
    def setupUi(self, editVendors50):
        editVendors50.setObjectName("editVendors50")
        editVendors50.resize(575, 549)
        editVendors50.setStyleSheet("*{\n"
"    \n"
"    \n"
"border:none;\n"
"background-color:transparent;\n"
"background:none;\n"
"padding:0;\n"
"margin:0;\n"
"color:#fff;\n"
"}\n"
"#QLineEdit{\n"
"color:black;\n"
"}\n"
"#QDateEdit{\n"
"color:black;}\n"
"\n"
"\n"
"#centralwidget{\n"
"background-color:#1f232a;\n"
"}\n"
"\n"
"QPushButton{\n"
"text-align:left;\n"
"padding: 5px 10px;\n"
"\n"
"border-top-left-radius:5px;\n"
"border-botton-left-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:grey;\n"
"text-align:left;\n"
"padding:2px 10px;\n"
"color:white;}")
        self.centralwidget = QtWidgets.QWidget(editVendors50)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.EditVendor = QtWidgets.QWidget(self.centralwidget)
        self.EditVendor.setObjectName("EditVendor")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.EditVendor)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.EditVendor)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(20)
        font.setBold(False)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.edit_vendor_options_frame = QtWidgets.QFrame(self.frame_3)
        self.edit_vendor_options_frame.setEnabled(True)
        self.edit_vendor_options_frame.setStyleSheet("QFrame {\n"
"    border: 2px solid white;\n"
"    border-radius: 15px;}\n"
"QPushButton:hover {\n"
"    background-color: lightblue;\n"
"}\n"
"\n"
"")
        self.edit_vendor_options_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.edit_vendor_options_frame.setObjectName("edit_vendor_options_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.edit_vendor_options_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.saveVendorChangesButton = QtWidgets.QPushButton(self.edit_vendor_options_frame)
        self.saveVendorChangesButton.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveVendorChangesButton.setFont(font)
        self.saveVendorChangesButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid grey;\n"
"    border-radius: 10px;\n"
"    text-align:center;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../latestUI/resources/Icons/diskette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveVendorChangesButton.setIcon(icon)
        self.saveVendorChangesButton.setDefault(False)
        self.saveVendorChangesButton.setFlat(False)
        self.saveVendorChangesButton.setObjectName("saveVendorChangesButton")
        self.horizontalLayout_5.addWidget(self.saveVendorChangesButton)
        self.undoVendorChangesButton = QtWidgets.QPushButton(self.edit_vendor_options_frame)
        self.undoVendorChangesButton.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.undoVendorChangesButton.setFont(font)
        self.undoVendorChangesButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid grey;\n"
"    border-radius: 10px;\n"
"  text-align:center;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../latestUI/resources/Icons/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undoVendorChangesButton.setIcon(icon1)
        self.undoVendorChangesButton.setObjectName("undoVendorChangesButton")
        self.horizontalLayout_5.addWidget(self.undoVendorChangesButton)
        self.removeVendorButton = QtWidgets.QPushButton(self.edit_vendor_options_frame)
        self.removeVendorButton.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.removeVendorButton.setFont(font)
        self.removeVendorButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid grey;\n"
"    border-radius: 10px;\n"
"  text-align:center;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../latestUI/resources/Icons/trash-can.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeVendorButton.setIcon(icon2)
        self.removeVendorButton.setObjectName("removeVendorButton")
        self.horizontalLayout_5.addWidget(self.removeVendorButton)
        self.gridLayout_6.addWidget(self.edit_vendor_options_frame, 2, 0, 1, 1)
        self.edit_vendor_details_frame = QtWidgets.QFrame(self.frame_3)
        self.edit_vendor_details_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.edit_vendor_details_frame.setObjectName("edit_vendor_details_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.edit_vendor_details_frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_89 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_89.setObjectName("label_89")
        self.gridLayout_5.addWidget(self.label_89, 5, 1, 1, 1)
        self.companiesEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.companiesEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #cccccc;\n"
"    border-radius: 20px; \n"
"color:black;\n"
"}\n"
"")
        self.companiesEdit.setObjectName("companiesEdit")
        self.gridLayout_5.addWidget(self.companiesEdit, 14, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 5, 0, 1, 1)
        self.baseUrlEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.baseUrlEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #cccccc;\n"
"    border-radius: 20px; \n"
"color:black;\n"
"}\n"
"")
        self.baseUrlEdit.setObjectName("baseUrlEdit")
        self.gridLayout_5.addWidget(self.baseUrlEdit, 5, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 0, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 12, 1, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.nameEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #cccccc;\n"
"    border-radius: 20px; \n"
"color:black;\n"
"}\n"
"")
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout_5.addWidget(self.nameEdit, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 11, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 8, 0, 1, 1)
        self.platformEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.platformEdit.setStyleSheet("background-color: #cccccc;")
        self.platformEdit.setObjectName("platformEdit")
        self.gridLayout_5.addWidget(self.platformEdit, 9, 3, 1, 1)
        self.name_validation_label = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.name_validation_label.setText("")
        self.name_validation_label.setObjectName("name_validation_label")
        self.gridLayout_5.addWidget(self.name_validation_label, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.edit_vendor_details_frame)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 1, 0, 1, 1)
        self.customerIdEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.customerIdEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #cccccc;\n"
"    border-radius: 20px; \n"
"color:black;\n"
"}\n"
"")
        self.customerIdEdit.setObjectName("customerIdEdit")
        self.gridLayout_5.addWidget(self.customerIdEdit, 7, 3, 1, 1)
        self.companiesText = QtWidgets.QLabel(self.edit_vendor_details_frame)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.companiesText.setFont(font)
        self.companiesText.setObjectName("companiesText")
        self.gridLayout_5.addWidget(self.companiesText, 14, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 7, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 13, 0, 1, 1)
        self.requestorIdEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.requestorIdEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #cccccc;\n"
"    border-radius: 20px; \n"
"color:black;\n"
"}\n"
"")
        self.requestorIdEdit.setObjectName("requestorIdEdit")
        self.gridLayout_5.addWidget(self.requestorIdEdit, 8, 3, 1, 1)
        self.descriptionEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descriptionEdit.sizePolicy().hasHeightForWidth())
        self.descriptionEdit.setSizePolicy(sizePolicy)
        self.descriptionEdit.setMinimumSize(QtCore.QSize(339, 0))
        self.descriptionEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #cccccc;\n"
"    border-radius: 20px; \n"
"color:black;\n"
"}\n"
"")
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.gridLayout_5.addWidget(self.descriptionEdit, 13, 3, 1, 1)
        self.url_validation_label = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.url_validation_label.setText("")
        self.url_validation_label.setObjectName("url_validation_label")
        self.gridLayout_5.addWidget(self.url_validation_label, 6, 3, 1, 1)
        self.is_non_sushi_edit = QtWidgets.QCheckBox(self.edit_vendor_details_frame)
        self.is_non_sushi_edit.setText("")
        self.is_non_sushi_edit.setObjectName("is_non_sushi_edit")
        self.gridLayout_5.addWidget(self.is_non_sushi_edit, 12, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 9, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.edit_vendor_details_frame)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 12, 0, 1, 1)
        self.apiKeyEdit = QtWidgets.QLineEdit(self.edit_vendor_details_frame)
        self.apiKeyEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #cccccc;\n"
"    border-radius: 20px; \n"
"color:black;\n"
"}\n"
"")
        self.apiKeyEdit.setObjectName("apiKeyEdit")
        self.gridLayout_5.addWidget(self.apiKeyEdit, 11, 3, 1, 1)
        self.gridLayout_6.addWidget(self.edit_vendor_details_frame, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.EditVendor, 0, 0, 1, 1)
        editVendors50.setCentralWidget(self.centralwidget)

        self.retranslateUi(editVendors50)
        QtCore.QMetaObject.connectSlotsByName(editVendors50)
        editVendors50.setTabOrder(self.nameEdit, self.baseUrlEdit)
        editVendors50.setTabOrder(self.baseUrlEdit, self.customerIdEdit)
        editVendors50.setTabOrder(self.customerIdEdit, self.requestorIdEdit)
        editVendors50.setTabOrder(self.requestorIdEdit, self.platformEdit)
        editVendors50.setTabOrder(self.platformEdit, self.apiKeyEdit)
        editVendors50.setTabOrder(self.apiKeyEdit, self.is_non_sushi_edit)
        editVendors50.setTabOrder(self.is_non_sushi_edit, self.descriptionEdit)
        editVendors50.setTabOrder(self.descriptionEdit, self.companiesEdit)
        editVendors50.setTabOrder(self.companiesEdit, self.saveVendorChangesButton)
        editVendors50.setTabOrder(self.saveVendorChangesButton, self.undoVendorChangesButton)
        editVendors50.setTabOrder(self.undoVendorChangesButton, self.removeVendorButton)

    def retranslateUi(self, editVendors50):
        _translate = QtCore.QCoreApplication.translate
        editVendors50.setWindowTitle(_translate("editVendors50", "MainWindow"))
        self.label_7.setText(_translate("editVendors50", "Edit Vendor "))
        self.saveVendorChangesButton.setText(_translate("editVendors50", "Save Changes"))
        self.undoVendorChangesButton.setText(_translate("editVendors50", "Undo Changes"))
        self.removeVendorButton.setText(_translate("editVendors50", "Remove Vendor"))
        self.label_89.setText(_translate("editVendors50", "*"))
        self.label_14.setText(_translate("editVendors50", "*"))
        self.label_2.setText(_translate("editVendors50", "Base URL"))
        self.label_20.setText(_translate("editVendors50", "5.0"))
        self.label_15.setText(_translate("editVendors50", "*"))
        self.label_5.setText(_translate("editVendors50", "API Key"))
        self.label_4.setText(_translate("editVendors50", "Requester ID"))
        self.label.setText(_translate("editVendors50", "Name"))
        self.companiesText.setText(_translate("editVendors50", "Companies"))
        self.label_3.setText(_translate("editVendors50", "Customer ID"))
        self.label_28.setText(_translate("editVendors50", "Description"))
        self.label_12.setText(_translate("editVendors50", "*"))
        self.label_6.setText(_translate("editVendors50", "Platform"))
        self.label_19.setText(_translate("editVendors50", "Version"))
        self.label_8.setText(_translate("editVendors50", "Is non sushi"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editVendors50 = QtWidgets.QMainWindow()
    ui = Ui_editVendors50()
    ui.setupUi(editVendors50)
    editVendors50.show()
    sys.exit(app.exec_())
