# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FetchProgressDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FetchProgressDialog(object):
    def setupUi(self, FetchProgressDialog):
        FetchProgressDialog.setObjectName("FetchProgressDialog")
        FetchProgressDialog.resize(800, 600)
        FetchProgressDialog.setMinimumSize(QtCore.QSize(680, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        FetchProgressDialog.setFont(font)
        FetchProgressDialog.setStyleSheet("QDialog {\n"
"background-color: #323232;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(FetchProgressDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fetching_frame = QtWidgets.QFrame(FetchProgressDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fetching_frame.sizePolicy().hasHeightForWidth())
        self.fetching_frame.setSizePolicy(sizePolicy)
        self.fetching_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fetching_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fetching_frame.setObjectName("fetching_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fetching_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.status_label = QtWidgets.QLabel(self.fetching_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.verticalLayout_2.addWidget(self.status_label)
        self.progress_bar = QtWidgets.QProgressBar(self.fetching_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar.sizePolicy().hasHeightForWidth())
        self.progress_bar.setSizePolicy(sizePolicy)
        self.progress_bar.setStyleSheet("QProgressBar {\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #05B8CC;\n"
"    width: 20px;\n"
"}")
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout_2.addWidget(self.progress_bar)
        self.verticalLayout.addWidget(self.fetching_frame)
        self.results_scroll_area = QtWidgets.QScrollArea(FetchProgressDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.results_scroll_area.sizePolicy().hasHeightForWidth())
        self.results_scroll_area.setSizePolicy(sizePolicy)
        self.results_scroll_area.setStyleSheet("QScrollArea {\n"
"    background-color: #1E1E1E;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"    background: #2A2A2A;\n"
"    width: 15px;\n"
"    margin: 15px 0 15px 0;\n"
"    border: 1px transparent #2A2A2A;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #5A5A5A;\n"
"    min-height: 20px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    background: none;\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    background: none;\n"
"    height: 0px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.results_scroll_area.setWidgetResizable(True)
        self.results_scroll_area.setObjectName("results_scroll_area")
        self.scroll_area_widget_contents = QtWidgets.QWidget()
        self.scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 776, 430))
        self.scroll_area_widget_contents.setObjectName("scroll_area_widget_contents")
        self.scroll_area_vertical_layout = QtWidgets.QVBoxLayout(self.scroll_area_widget_contents)
        self.scroll_area_vertical_layout.setObjectName("scroll_area_vertical_layout")
        self.results_scroll_area.setWidget(self.scroll_area_widget_contents)
        self.verticalLayout.addWidget(self.results_scroll_area)
        self.horizontalFrame = QtWidgets.QFrame(FetchProgressDialog)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.log_file_button = QtWidgets.QPushButton(self.horizontalFrame)
        self.log_file_button.setStyleSheet("QPushButton {\n"
"    background-color: #1768E3; \n"
"    color: #FFFFFF;\n"
"    font: bold;\n"
"   border-radius: 4px;\n"
"text-align: center;\n"
"font-size: 14px;\n"
"padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: #2095E6;\n"
"}\n"
"\n"
"")
        self.log_file_button.setObjectName("log_file_button")
        self.horizontalLayout.addWidget(self.log_file_button, 0, QtCore.Qt.AlignLeft)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.horizontalFrame)
        self.buttonBox.setStyleSheet("border: 2px solid grey;\n"
"border-radius: 8px;\n"
"background-color: #000000;\n"
"font-size: 14px;\n"
"padding: 4px;")
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.horizontalFrame)

        self.retranslateUi(FetchProgressDialog)
        QtCore.QMetaObject.connectSlotsByName(FetchProgressDialog)
        FetchProgressDialog.setTabOrder(self.results_scroll_area, self.log_file_button)

    def retranslateUi(self, FetchProgressDialog):
        _translate = QtCore.QCoreApplication.translate
        FetchProgressDialog.setWindowTitle(_translate("FetchProgressDialog", "Fetch Progress"))
        self.status_label.setText(_translate("FetchProgressDialog", "Fetching..."))
        self.log_file_button.setText(_translate("FetchProgressDialog", "Log File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FetchProgressDialog = QtWidgets.QDialog()
    ui = Ui_FetchProgressDialog()
    ui.setupUi(FetchProgressDialog)
    FetchProgressDialog.show()
    sys.exit(app.exec_())
