# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MoreOptionsMasterReport.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MoreOptionsDialog(object):
    def setupUi(self, MoreOptionsDialog):
        MoreOptionsDialog.setObjectName("MoreOptionsDialog")
        MoreOptionsDialog.resize(375, 430)
        self.centralwidget = QtWidgets.QWidget(MoreOptionsDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 9, 371, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setSizeIncrement(QtCore.QSize(50, 0))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.options_frame_main = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.options_frame_main.setStyleSheet("QFrame{\n"
"color: \"white\";\n"
"}")
        self.options_frame_main.setObjectName("options_frame_main")
        self.options_frame = QtWidgets.QGridLayout(self.options_frame_main)
        self.options_frame.setObjectName("options_frame")
        self.verticalLayout.addWidget(self.options_frame_main, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        MoreOptionsDialog.setCentralWidget(self.centralwidget)

        self.retranslateUi(MoreOptionsDialog)
        QtCore.QMetaObject.connectSlotsByName(MoreOptionsDialog)

    def retranslateUi(self, MoreOptionsDialog):
        _translate = QtCore.QCoreApplication.translate
        MoreOptionsDialog.setWindowTitle(_translate("MoreOptionsDialog", "MainWindow"))
        self.label.setText(_translate("MoreOptionsDialog", "Options"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MoreOptionsDialog = QtWidgets.QMainWindow()
    ui = Ui_MoreOptionsDialog()
    ui.setupUi(MoreOptionsDialog)
    MoreOptionsDialog.show()
    sys.exit(app.exec_())
