# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RemoveVendorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_remove(object):
    def setupUi(self, Dialog_remove):
        Dialog_remove.setObjectName("Dialog_remove")
        Dialog_remove.resize(592, 143)
        Dialog_remove.setStyleSheet("*{\n"
"    \n"
"border:none;\n"
"background-color:transparent;\n"
"background:none;\n"
"padding:0;\n"
"margin:0;\n"
"color:#fff;\n"
"}\n"
"\n"
"\n"
"\n"
"#QDialog{\n"
"background-color:#1f232a;\n"
"}\n"
"\n"
"QDialog{\n"
"text-align:left;\n"
"padding: 5px 10px;\n"
"\n"
"border-top-left-radius:5px;\n"
"border-botton-left-radius:5px;\n"
"}\n"
"QDialog{\n"
"background-color:#1f232a;;\n"
"text-align:left;\n"
"padding:2px 10px;\n"
"color:white;}")
        self.label = QtWidgets.QLabel(Dialog_remove)
        self.label.setGeometry(QtCore.QRect(10, 10, 561, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Dialog_remove)
        self.widget.setGeometry(QtCore.QRect(220, 70, 331, 61))
        self.widget.setStyleSheet("QPushButton:pressed {\n"
"    background-color: rgb(197, 197, 197);\n"
"    \n"
"}\n"
"\n"
"QPushButton{\n"
"border:2px solid grey;\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(Dialog_remove)
        QtCore.QMetaObject.connectSlotsByName(Dialog_remove)

    def retranslateUi(self, Dialog_remove):
        _translate = QtCore.QCoreApplication.translate
        Dialog_remove.setWindowTitle(_translate("Dialog_remove", "Dialog"))
        self.label.setText(_translate("Dialog_remove", "Are you sure you want to remove this vendor?"))
        self.pushButton.setText(_translate("Dialog_remove", "OK"))
        self.pushButton_2.setText(_translate("Dialog_remove", "CANCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_remove = QtWidgets.QDialog()
    ui = Ui_Dialog_remove()
    ui.setupUi(Dialog_remove)
    Dialog_remove.show()
    sys.exit(app.exec_())
