# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VendorResultsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VendorResultsWidget(object):
    def setupUi(self, VendorResultsWidget):
        VendorResultsWidget.setObjectName("VendorResultsWidget")
        VendorResultsWidget.resize(600, 255)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VendorResultsWidget.sizePolicy().hasHeightForWidth())
        VendorResultsWidget.setSizePolicy(sizePolicy)
        VendorResultsWidget.setMinimumSize(QtCore.QSize(600, 0))
        VendorResultsWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        VendorResultsWidget.setFont(font)
        VendorResultsWidget.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(VendorResultsWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.vendor_result_frame = QtWidgets.QFrame(VendorResultsWidget)
        self.vendor_result_frame.setMaximumSize(QtCore.QSize(600, 16777215))
        self.vendor_result_frame.setStyleSheet("#vendor_result_frame{\n"
" border: 2px solid gray;\n"
"border-radius: 4px;\n"
"\n"
"}")
        self.vendor_result_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.vendor_result_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vendor_result_frame.setObjectName("vendor_result_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.vendor_result_frame)
        self.gridLayout_2.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.status_label = QtWidgets.QLabel(self.vendor_result_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status_label.sizePolicy().hasHeightForWidth())
        self.status_label.setSizePolicy(sizePolicy)
        self.status_label.setMinimumSize(QtCore.QSize(100, 0))
        self.status_label.setStyleSheet("font: bold;")
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.gridLayout_2.addWidget(self.status_label, 0, 4, 1, 1)
        self.results_frame = QtWidgets.QFrame(self.vendor_result_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.results_frame.sizePolicy().hasHeightForWidth())
        self.results_frame.setSizePolicy(sizePolicy)
        self.results_frame.setMinimumSize(QtCore.QSize(0, 200))
        self.results_frame.setStyleSheet("")
        self.results_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.results_frame.setObjectName("results_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.results_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.successful_list_box = QtWidgets.QFrame(self.results_frame)
        self.successful_list_box.setStyleSheet("color:#83DBB2;")
        self.successful_list_box.setObjectName("successful_list_box")
        self.successful_box = QtWidgets.QHBoxLayout(self.successful_list_box)
        self.successful_box.setObjectName("successful_box")
        self.label = QtWidgets.QLabel(self.successful_list_box)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.successful_box.addWidget(self.label)
        self.successful_reports_list = QtWidgets.QLabel(self.successful_list_box)
        self.successful_reports_list.setText("")
        self.successful_reports_list.setObjectName("successful_reports_list")
        self.successful_box.addWidget(self.successful_reports_list)
        self.verticalLayout.addWidget(self.successful_list_box)
        self.warning_list_box = QtWidgets.QFrame(self.results_frame)
        self.warning_list_box.setStyleSheet("\n"
"color: #DBA875;\n"
"")
        self.warning_list_box.setObjectName("warning_list_box")
        self.warning_box = QtWidgets.QHBoxLayout(self.warning_list_box)
        self.warning_box.setObjectName("warning_box")
        self.label_4 = QtWidgets.QLabel(self.warning_list_box)
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName("label_4")
        self.warning_box.addWidget(self.label_4)
        self.warning_reports_list = QtWidgets.QLabel(self.warning_list_box)
        self.warning_reports_list.setText("")
        self.warning_reports_list.setObjectName("warning_reports_list")
        self.warning_box.addWidget(self.warning_reports_list)
        self.verticalLayout.addWidget(self.warning_list_box)
        self.failed_list_box = QtWidgets.QFrame(self.results_frame)
        self.failed_list_box.setStyleSheet("color: #D5A7AF;")
        self.failed_list_box.setObjectName("failed_list_box")
        self.failed_box = QtWidgets.QHBoxLayout(self.failed_list_box)
        self.failed_box.setObjectName("failed_box")
        self.label_6 = QtWidgets.QLabel(self.failed_list_box)
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setObjectName("label_6")
        self.failed_box.addWidget(self.label_6)
        self.failed_reports_list = QtWidgets.QLabel(self.failed_list_box)
        self.failed_reports_list.setText("")
        self.failed_reports_list.setObjectName("failed_reports_list")
        self.failed_box.addWidget(self.failed_reports_list)
        self.verticalLayout.addWidget(self.failed_list_box)
        self.cancelled_list_box = QtWidgets.QFrame(self.results_frame)
        self.cancelled_list_box.setObjectName("cancelled_list_box")
        self.cancelled_box = QtWidgets.QHBoxLayout(self.cancelled_list_box)
        self.cancelled_box.setObjectName("cancelled_box")
        self.label_8 = QtWidgets.QLabel(self.cancelled_list_box)
        self.label_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_8.setObjectName("label_8")
        self.cancelled_box.addWidget(self.label_8)
        self.cancelled_reports_list = QtWidgets.QLabel(self.cancelled_list_box)
        self.cancelled_reports_list.setText("")
        self.cancelled_reports_list.setObjectName("cancelled_reports_list")
        self.cancelled_box.addWidget(self.cancelled_reports_list)
        self.verticalLayout.addWidget(self.cancelled_list_box)
        self.gridLayout_2.addWidget(self.results_frame, 1, 1, 1, 5)
        self.vendor_label = QtWidgets.QLabel(self.vendor_result_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vendor_label.sizePolicy().hasHeightForWidth())
        self.vendor_label.setSizePolicy(sizePolicy)
        self.vendor_label.setStyleSheet("QLabel {\n"
" font-size: 16px;\n"
"padding-left: 10px;\n"
"}")
        self.vendor_label.setObjectName("vendor_label")
        self.gridLayout_2.addWidget(self.vendor_label, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.vendor_result_frame, 0, 0, 1, 1)

        self.retranslateUi(VendorResultsWidget)
        QtCore.QMetaObject.connectSlotsByName(VendorResultsWidget)

    def retranslateUi(self, VendorResultsWidget):
        _translate = QtCore.QCoreApplication.translate
        VendorResultsWidget.setWindowTitle(_translate("VendorResultsWidget", "Form"))
        self.status_label.setText(_translate("VendorResultsWidget", "Success"))
        self.label.setText(_translate("VendorResultsWidget", "SUCCESSFUL : "))
        self.label_4.setText(_translate("VendorResultsWidget", "WARNING : "))
        self.label_6.setText(_translate("VendorResultsWidget", "FAILED : "))
        self.label_8.setText(_translate("VendorResultsWidget", "CANCELLED : "))
        self.vendor_label.setText(_translate("VendorResultsWidget", "Bioone"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VendorResultsWidget = QtWidgets.QWidget()
    ui = Ui_VendorResultsWidget()
    ui.setupUi(VendorResultsWidget)
    VendorResultsWidget.show()
    sys.exit(app.exec_())
